import './globals.css'
import type { Metadata } from 'next'
import { Jomhuria } from 'next/font/google'

const inter = Jomhuria({ 
  subsets: ['latin'],
  weight: '400' // Add the 'weight' property with an appropriate value
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  )
}
